/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package olc1s2020_practica1;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author aiyel
 */
public class Interfaz_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Usuairo
     */
    JFileChooser chooserFile = new JFileChooser();
    File document;
    FileInputStream inFile;
    FileOutputStream outFile;
    private LinkedList<ExpresionRegular> list_exp_reg;
    private LinkedList<Conjunto> conjuntos;
    private String contenido;
    private LinkedList<String> comandos;
    public String body;
    //private LinkedList<Entrada> entradas;
    
    public Interfaz_Usuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.contenido = "";
        this.list_exp_reg = new LinkedList<>();
        this.conjuntos = new LinkedList<>();
        this.comandos = new LinkedList<>();
        body = "";
    }
    
    public String abrirArchivo(File document){
        String cuerpo = "";
        try {
                inFile = new FileInputStream(document);
                int ascci;
                while((ascci=inFile.read())!=-1){
                    char caracter = (char)ascci;
                    cuerpo += caracter;
                }
            } catch (IOException ex) {
                Logger.getLogger(Interfaz_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        return cuerpo;
    }
    
    public void guardarComo(){
        
    }
    
    private void analizar(String contenido_analizar){
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_area_entrada = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textarea_salida = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        generarAutomatas = new javax.swing.JButton();
        analizarEntradas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Análisis Léxico");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Contenido archivo de entrada");

        tf_area_entrada.setColumns(20);
        tf_area_entrada.setRows(5);
        jScrollPane1.setViewportView(tf_area_entrada);

        textarea_salida.setColumns(20);
        textarea_salida.setRows(5);
        jScrollPane2.setViewportView(textarea_salida);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Salida");

        generarAutomatas.setText("Generar Automatas");
        generarAutomatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarAutomatasActionPerformed(evt);
            }
        });

        analizarEntradas.setText("Analizar Entradas");
        analizarEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarEntradasActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem4.setText("Abrir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setText("Guardar");
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Guardar Como");
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Generar Salida");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generarAutomatas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(analizarEntradas))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(456, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generarAutomatas)
                    .addComponent(analizarEntradas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        if(chooserFile.showDialog(null, "Abrir")==JFileChooser.APPROVE_OPTION){
            document=chooserFile.getSelectedFile();
            if(document.canRead()){
                analizarEntradas.setEnabled(true);
                if(document.getName().endsWith("er")){
                    String texto = abrirArchivo(document);
                    //jLabel2.setText("Archivo:  "+document.getName().toString());
                    body = texto;
                    tf_area_entrada.setText(body);
                                        
                }else{
                    JOptionPane.showMessageDialog(null,"Archivo invalido!");
                }
            }
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void generarAutomatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarAutomatasActionPerformed
        // TODO add your handling code here:
        Analizador lexico = new Analizador();
        if(!tf_area_entrada.getText().equals("")){
            lexico.analisis(tf_area_entrada.getText());
        }else{
            JOptionPane.showMessageDialog(null,"No hay archivo cargado en el area de entrada!");
        }
    }//GEN-LAST:event_generarAutomatasActionPerformed

    private void analizarEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarEntradasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_analizarEntradasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizarEntradas;
    private javax.swing.JButton generarAutomatas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textarea_salida;
    private javax.swing.JTextArea tf_area_entrada;
    // End of variables declaration//GEN-END:variables
}
